### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by rogerfederal** [matthewszeto/91PornForumScraper#1]

**Comment by matthewszeto** [comment]
你只要有安裝python，你就正常地import library用就可以了

**Comment by rogerfederal** [comment]
> 你只要有安裝python，你就正常地import library用就可以了
我试了一下，依赖包均已安装
先运行python Scrapper.py 还是先运行ForumThread.py  ，要不要在这两个PY文件中 调用该方法呢？

**Comment by rogerfederal** [comment]
> 你只要有安裝python，你就正常地import library用就可以了
是不是要重新写一个方法，实例化一个对象，然后调用函数，入口在哪里，我对Python不是很熟

**Comment by matthewszeto** [comment]
不打緊，我懂你的意思了，你不知道如何調這個library。我現在加了一個class名叫demo，你execute那一個class就可以了。所以你想改動的話，也只要on top of it 進行修改就可以了。
還有，ForumThread.py只是一個類似java 平時的entity class，只是建立object方便store東西，他是沒有任何實際作用的。

**Comment by matthewszeto** [comment]
如果你在使用的過程還有任何問題的話，或者是有任何新功能的建議，你可以告訴我。
要是你覺得這個東西有趣的話，歡迎follow 我 和 給這個library star
